<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Please choose_css-ackcql</name>
   <tag></tag>
   <elementGuidId>6416f4c9-a105-4b6e-a9bf-a7d2931594f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/section/div/div/div[2]/div/div/form/div/div/div[3]/div/div/div[2]/div/div/div/div/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>76f181e4-f399-4c1c-8ddd-2698eb0d57f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> css-ackcql</value>
      <webElementGuid>c816deb6-4923-4693-81b9-c50021ae488c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;content-wrapper&quot;]/div[@class=&quot;container-fluid pb-5&quot;]/section[@class=&quot;content&quot;]/div[@class=&quot;mt-2&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-9&quot;]/div[@class=&quot;tab-content&quot;]/div[@class=&quot;fade tab-pane active show&quot;]/form[@class=&quot;general_information&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body&quot;]/div[3]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 col-md-12 col-sm-9&quot;]/div[@class=&quot;form-group form-group row&quot;]/div[@class=&quot;col-lg-9 col-md-8&quot;]/div[1]/div[@class=&quot;react-select null css-b62m3t-container&quot;]/div[@class=&quot;css-10cm8zn-control&quot;]/div[@class=&quot;css-1d8n9bt&quot;]/div[@class=&quot;css-ackcql&quot;]</value>
      <webElementGuid>94cc5a6f-913a-40b0-a828-a1ad5f2474dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/section/div/div/div[2]/div/div/form/div/div/div[3]/div/div/div[2]/div/div/div/div/div/div[2]</value>
      <webElementGuid>62d89303-491c-42e1-a846-b5275ee27a00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please choose'])[1]/following::div[1]</value>
      <webElementGuid>1fa86a11-d392-4fcb-8682-9d16a3b23421</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[8]/following::div[7]</value>
      <webElementGuid>93460bb5-f0e7-4612-b205-1405c499f36a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[1]/preceding::div[3]</value>
      <webElementGuid>94835cc9-c742-4ab7-9df2-29c557b54327</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='State/ Province'])[1]/preceding::div[6]</value>
      <webElementGuid>6b01c4b5-4648-4039-89ab-4b346cb2f766</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div[2]</value>
      <webElementGuid>909c0506-e705-48a6-88e8-a6682cf4e74b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
