<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Please choose_css-ackcql_1</name>
   <tag></tag>
   <elementGuidId>52d146b2-2b03-454c-b45c-4e8ec5bce4b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/section/div/div/div[2]/div/div/form/div/div/div[4]/div/div/div[2]/div/div/div/div/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b717b577-6b07-4a55-bdaa-a0ced2f33a82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> css-ackcql</value>
      <webElementGuid>5485fe1d-038e-4d63-ad6c-ed7542462f85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;content-wrapper&quot;]/div[@class=&quot;container-fluid pb-5&quot;]/section[@class=&quot;content&quot;]/div[@class=&quot;mt-2&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-9&quot;]/div[@class=&quot;tab-content&quot;]/div[@class=&quot;fade tab-pane active show&quot;]/form[@class=&quot;general_information&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body&quot;]/div[4]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 col-md-12 col-sm-9&quot;]/div[@class=&quot;form-group form-group row&quot;]/div[@class=&quot;col-lg-9 col-md-8&quot;]/div[1]/div[@class=&quot;react-select null css-b62m3t-container&quot;]/div[@class=&quot;css-10cm8zn-control&quot;]/div[@class=&quot;css-1d8n9bt&quot;]/div[@class=&quot;css-ackcql&quot;]</value>
      <webElementGuid>1b8d2616-399e-4492-9e40-cad929c6fbe7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/section/div/div/div[2]/div/div/form/div/div/div[4]/div/div/div[2]/div/div/div/div/div/div[2]</value>
      <webElementGuid>473b7fa4-2477-476f-b2f8-6da9a65f43da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please choose'])[3]/following::div[1]</value>
      <webElementGuid>93eeb0f4-ca5f-4e27-a151-18cc38bad1c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[9]/following::div[7]</value>
      <webElementGuid>ec3e0f55-fa7e-4991-a237-cc33dfcc05da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[1]/preceding::div[3]</value>
      <webElementGuid>10f8213c-02c7-4b58-9038-57d5f8973999</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='State/ Province'])[2]/preceding::div[6]</value>
      <webElementGuid>74bdcb50-89c6-4309-a4f0-efb0373bbda5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/div/div/div/div/div/div[2]</value>
      <webElementGuid>e4ffc234-7ce2-4c12-9522-9d0038958ebb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
