<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__startDate_</name>
   <tag></tag>
   <elementGuidId>1db1431e-3500-4b88-b0e1-1e94a4aa6dff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#startDate_</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='startDate_']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5cfbf107-1de2-4202-a513-b2375df4ba4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3eb835e7-5f07-49fa-9ceb-90eb07371db0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control </value>
      <webElementGuid>ffb1ea65-5505-4e68-a29f-d1e6d6e35a73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>startDate_</value>
      <webElementGuid>ac4ab906-04ca-4b33-9f5c-93b528afa1a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>fc745385-c75a-45c5-920e-87a8bf1952f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>12 January 2023</value>
      <webElementGuid>c282416a-7778-4a6a-95e3-a3ef5d482525</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;startDate_&quot;)</value>
      <webElementGuid>e4e6c29e-d0f6-4cd0-bdac-2093cce868f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='startDate_']</value>
      <webElementGuid>a2cf3a23-f323-44d9-9f95-c36c0e759def</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/section/div/div/div[2]/div/div/form/div/div/div/div/div/div[6]/div/div/div/div/div/div/div/input</value>
      <webElementGuid>ec7ef6fa-00f2-4207-9e55-0b0fe0f2ca28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div/div/div/div/input</value>
      <webElementGuid>2bc175eb-91cd-482b-a1bb-c4c70472376a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'startDate_']</value>
      <webElementGuid>5a66ff5b-e57c-4d29-a263-ebd4c7c4b80f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
