<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__corporate_code</name>
   <tag></tag>
   <elementGuidId>78dc745f-498b-4953-a906-ddae5efede25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#corporate_code</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='corporate_code']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fd0eb625-f736-4b6f-b1a8-0a764f0ae613</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>corporate_code</value>
      <webElementGuid>768a60f9-6246-4ef7-9d77-f4b37787e240</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>7d317c52-5f99-44d5-afa3-9783fd82adf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>36</value>
      <webElementGuid>e0aee151-823b-4d8c-8627-bc332c355155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b8841ec1-0a6c-48c1-82b1-aabdfaad517c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>corporate_code</value>
      <webElementGuid>25588407-5611-479c-a9e0-3955ba253454</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>3abfdad6-0652-493c-91e8-0fc841a23e16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;corporate_code&quot;)</value>
      <webElementGuid>ce340d28-da4f-4731-9d7a-a2927fbc78fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='corporate_code']</value>
      <webElementGuid>497a900c-0be8-42ac-a169-9bd3b9f5e270</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/section/div/div/div[2]/div/div/form/div/div/div/div/div/div/div/input</value>
      <webElementGuid>cbf0d989-662b-4a88-b2f3-bfb1b6024cff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>c5744e36-c136-4ac3-84ea-086562284c46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'corporate_code' and @type = 'text' and @id = 'corporate_code']</value>
      <webElementGuid>8ebd2c5c-b841-4151-bfb7-c455a7bfc003</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
