<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_12</name>
   <tag></tag>
   <elementGuidId>ed903f2f-df8a-4bd5-86a9-b3efbd64c3a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Sat'])[1]/following::span[12]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>28fffc95-9592-457d-9720-f06b5de98f88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sd </value>
      <webElementGuid>51af183f-d6e6-4cd0-9ed3-7d3f798d14e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>f758dca9-ef9f-4bf4-934f-38d6fd229b2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;sidebar-mini layout-fixed control-sidebar-slide-open sidebar-collapse&quot;]/div[3]/div[2]/div[1]/div[@class=&quot;rmdp-wrapper rmdp-shadow&quot;]/div[@class=&quot;rmdp-top-class&quot;]/div[@class=&quot;rmdp-calendar&quot;]/div[2]/div[@class=&quot;rmdp-day-picker&quot;]/div[1]/div[@class=&quot;rmdp-week&quot;]/div[@class=&quot;rmdp-day rmdp-today rmdp-range start end&quot;]/span[@class=&quot;sd&quot;]</value>
      <webElementGuid>e0025f83-4905-4b70-ad54-493f0bbdba7e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sat'])[1]/following::span[12]</value>
      <webElementGuid>e4b117a3-ea81-4840-82be-b4986e8f2714</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fri'])[1]/following::span[12]</value>
      <webElementGuid>5cac2c0f-0d6c-4d3f-a639-7356c9526c0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sun'])[2]/preceding::span[24]</value>
      <webElementGuid>1fa8473c-04be-4448-af71-8c1c4b9784dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mon'])[2]/preceding::span[24]</value>
      <webElementGuid>c12861ea-6778-457d-b80d-caec35084fc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='12']/parent::*</value>
      <webElementGuid>6a55c88e-cad0-4437-8cae-f433d51a7e24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[5]/span</value>
      <webElementGuid>db58583b-545e-4d81-81af-287dfbd34387</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '12' or . = '12')]</value>
      <webElementGuid>1d499d84-50c6-4376-9bd1-269f820a4870</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
