<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Record 321 - Age Qualifying Type Name (_29f3cb</name>
   <tag></tag>
   <elementGuidId>add1642f-eaab-45bb-9c17-598243963740</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.Snackbar_snackbar__text__1Hx2a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[3]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>90c4a899-f513-46ff-ad46-245f35aaf0bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Snackbar_snackbar__text__1Hx2a</value>
      <webElementGuid>7b685bd8-a6d6-4314-8e48-baf7582a09af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Record 321 - Age Qualifying Type Name (Automation) has been successfully saved.</value>
      <webElementGuid>63d4d419-e536-4ad0-9312-e7212776671c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;Snackbar_snackbar-wrapper__ocbPJ Snackbar_snackbar-wrapper-bottom-right__8wQeQ&quot;]/div[@class=&quot;Snackbar_snackbar__GsYZl&quot;]/div[@class=&quot;Snackbar_snackbar__text__1Hx2a&quot;]</value>
      <webElementGuid>9243e6f9-4fb3-40dd-b806-f033070a7a5b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div/div</value>
      <webElementGuid>d42510de-0374-4666-9d25-31b33b3f2306</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Powered by:'])[1]/following::div[4]</value>
      <webElementGuid>fbf23632-68a7-4f9e-b939-45f0ed913a47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Record 321 - Age Qualifying Type Name (Automation) has been successfully saved.']/parent::*</value>
      <webElementGuid>0b89b15d-b80e-4e27-b2c9-5e7bce38d5b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div</value>
      <webElementGuid>5a022a4c-45d0-4223-a244-7495f654f62a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Record 321 - Age Qualifying Type Name (Automation) has been successfully saved.' or . = 'Record 321 - Age Qualifying Type Name (Automation) has been successfully saved.')]</value>
      <webElementGuid>34926c47-b5e1-4f42-bc17-42a3fa100c1f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
