<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Actions_float-left select-checkbox-it_8952ca</name>
   <tag></tag>
   <elementGuidId>6ec21ba4-f9e4-4daf-9d05-f155211465aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.float-left.select-checkbox-item.ml-2.mr-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='checkbox'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a806b483-f85f-41f2-b6b0-1abf7e9a2fc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>ddc7ea81-79a2-4e7a-9cd1-9d4634cc3bd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>217cfe27-ca79-4a7f-89af-6f9a82fbbbbf</value>
      <webElementGuid>1dd4eed6-4909-4a38-994a-f5dbf87b26a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>float-left select-checkbox-item ml-2 mr-1</value>
      <webElementGuid>559c7dd9-0e0b-42d8-aac8-9c0b6eb4834a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DataTables_Table_1&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;select-checkbox dtr-control&quot;]/input[@class=&quot;float-left select-checkbox-item ml-2 mr-1&quot;]</value>
      <webElementGuid>184aaa2b-19ea-4d75-8879-1feb5ce07e45</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='checkbox'])[2]</value>
      <webElementGuid>ed553f71-f7e3-4d7d-b92e-ad6beba1f770</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='DataTables_Table_1']/tbody/tr/td/input</value>
      <webElementGuid>bcc54bef-2f92-47b7-aa81-8acf0e5bd3a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>8df2734f-81e0-48dc-b4b8-6991c4e38ab4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>f078e6ba-b03a-44f5-9d4d-2318240a59ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
