<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>adv_status</name>
   <tag></tag>
   <elementGuidId>e9f33571-1f99-4171-a86e-cb81a3c178cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>.filter-fixer-corp-user-mgmnt</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.filter-fixer-corp-user-mgmnt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
