<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>data_appears</name>
   <tag></tag>
   <elementGuidId>9d9ee8a3-03d0-46dd-8080-55ccb227555c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//tr)[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
