<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Aircraft</name>
   <tag></tag>
   <elementGuidId>48250384-9dab-4f6d-baf0-23a134f70964</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='d14be77b-679e-5f33-aab7-f6719e54180a']/ul/li[2]/a/p</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Aircraft' or . = 'Aircraft')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p[title=&quot;Aircraft&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>cbd79ae1-07d8-41e7-a5c4-0457613e9339</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Aircraft</value>
      <webElementGuid>1997dcb3-24b7-45ef-a66b-42b9f67fa71c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Aircraft</value>
      <webElementGuid>5204a350-fc71-4592-980e-198a3cc9b010</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;d14be77b-679e-5f33-aab7-f6719e54180a&quot;)/ul[@class=&quot;nav nav-treeview&quot;]/li[@class=&quot;nav-item&quot;]/a[@class=&quot;nav-link&quot;]/p[1]</value>
      <webElementGuid>16b5d590-631e-4c31-867a-ccc5d6d10401</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='d14be77b-679e-5f33-aab7-f6719e54180a']/ul/li[2]/a/p</value>
      <webElementGuid>15133b74-5a5e-465d-9c26-84df5234b398</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IDR'])[1]/following::p[4]</value>
      <webElementGuid>a9d50cfe-69a5-482a-a34c-51e023db17e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Master Data Management'])[2]/preceding::p[60]</value>
      <webElementGuid>e77ccf3c-a181-414c-a2af-3d38dd5f6440</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Age Qualifying Types'])[1]/preceding::p[60]</value>
      <webElementGuid>ba42ad22-a7c8-4497-bb73-f47682aa492d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Aircraft']/parent::*</value>
      <webElementGuid>30712cd0-db35-4c02-af2e-a02161e72724</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li[2]/a/p</value>
      <webElementGuid>2e8d2260-e482-4e42-9d7c-0559db4e8b1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@title = 'Aircraft' and (text() = 'Aircraft' or . = 'Aircraft')]</value>
      <webElementGuid>c0f7e6bc-0711-43a0-8002-9876fbacce55</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
