<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Country</name>
   <tag></tag>
   <elementGuidId>ecffd10b-d283-4d29-89d4-10097d4ca455</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p[title=&quot;Country&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='d14be77b-679e-5f33-aab7-f6719e54180a']/ul/li[9]/a/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>d20bc7d7-9531-4a9d-84e0-c91bbcccdb76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Country</value>
      <webElementGuid>8c25785e-4d4d-419f-baff-d5801fdd43a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Country</value>
      <webElementGuid>d3805e8a-e174-48b4-ab86-e83ef32f9276</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;d14be77b-679e-5f33-aab7-f6719e54180a&quot;)/ul[@class=&quot;nav nav-treeview&quot;]/li[@class=&quot;nav-item&quot;]/a[@class=&quot;nav-link&quot;]/p[1]</value>
      <webElementGuid>1c2695d6-de4c-4dec-903b-00d8c61053dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='d14be77b-679e-5f33-aab7-f6719e54180a']/ul/li[9]/a/p</value>
      <webElementGuid>9c9d08d5-fe83-4315-92b7-a17108ae306f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IDR'])[1]/following::p[11]</value>
      <webElementGuid>000b433d-68f8-4950-bc7c-8c5ed7fd178d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Master Data Management'])[2]/preceding::p[53]</value>
      <webElementGuid>e1c69c02-3204-494e-8eb0-ebf338980845</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cities'])[1]/preceding::p[53]</value>
      <webElementGuid>d40125ff-4c73-4202-a2a5-78b2d35a51ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Country']/parent::*</value>
      <webElementGuid>0819f6e4-e7da-4014-a14f-7dfe496fbbbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[9]/a/p</value>
      <webElementGuid>6af54388-44c1-49df-9962-ca4ff40f0f0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@title = 'Country' and (text() = 'Country' or . = 'Country')]</value>
      <webElementGuid>97f87e9c-29ff-4990-af62-fd069a2014d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
