<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Region</name>
   <tag></tag>
   <elementGuidId>9f4aaa31-1fd3-4397-bcaa-dd84d6efbdff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p[title=&quot;Region&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='d14be77b-679e-5f33-aab7-f6719e54180a']/ul/li[27]/a/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>f8ea9f45-aa48-4359-8dc9-25226916eec6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Region</value>
      <webElementGuid>3913d86d-9041-4b8b-ac1c-1b48aae8c151</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Region</value>
      <webElementGuid>62a74a01-41d0-4fc5-b1e8-6b6f9bbf516e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;d14be77b-679e-5f33-aab7-f6719e54180a&quot;)/ul[@class=&quot;nav nav-treeview&quot;]/li[@class=&quot;nav-item&quot;]/a[@class=&quot;nav-link&quot;]/p[1]</value>
      <webElementGuid>fdd8c4b4-1653-45c6-9d09-6dd11bf470ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='d14be77b-679e-5f33-aab7-f6719e54180a']/ul/li[27]/a/p</value>
      <webElementGuid>d70716ef-1d01-463f-8783-e4e5eeda4bed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IDR'])[1]/following::p[29]</value>
      <webElementGuid>1a47260d-49ce-4f86-894c-cb36680788ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Master Data Management'])[2]/preceding::p[35]</value>
      <webElementGuid>7c200e9a-a862-4ab4-a14f-477fa7f9c627</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rating Types'])[1]/preceding::p[35]</value>
      <webElementGuid>e0da7d66-4e3f-4b0a-bb8d-df8533aec46d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Region']/parent::*</value>
      <webElementGuid>923bdb45-4d8d-4aaf-b947-97832ea00e71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[27]/a/p</value>
      <webElementGuid>48adf9eb-2886-45ce-b6d3-ebfaaaef6832</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@title = 'Region' and (text() = 'Region' or . = 'Region')]</value>
      <webElementGuid>feeb6472-059c-4478-b5af-eac8c5c16f75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
