<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Zones</name>
   <tag></tag>
   <elementGuidId>8d6d74e9-5d5a-4384-a82f-28eb9b83c5dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p[title=&quot;Zones&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='d14be77b-679e-5f33-aab7-f6719e54180a']/ul/li[36]/a/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>d8baa7ef-10e9-4e35-b50b-f9a73c4593c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Zones</value>
      <webElementGuid>a0714996-e420-401f-b2f5-8279aba65cb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Zones</value>
      <webElementGuid>593750ae-fbad-46e0-9fa9-44cc4044aabf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;d14be77b-679e-5f33-aab7-f6719e54180a&quot;)/ul[@class=&quot;nav nav-treeview&quot;]/li[@class=&quot;nav-item&quot;]/a[@class=&quot;nav-link&quot;]/p[1]</value>
      <webElementGuid>1aa03f4e-49a5-45b7-997b-7f08db9acf4e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='d14be77b-679e-5f33-aab7-f6719e54180a']/ul/li[36]/a/p</value>
      <webElementGuid>bbd6735d-5421-4b3f-a38a-8f0823e15786</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IDR'])[1]/following::p[38]</value>
      <webElementGuid>98cd4797-b094-4dea-8672-2f13ab145370</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Master Data Management'])[2]/preceding::p[26]</value>
      <webElementGuid>9718ce7c-260f-4aba-ba76-a2b7cf993537</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trip Types'])[1]/preceding::p[26]</value>
      <webElementGuid>aa6d133e-7a6a-45ec-a64f-ecff6a2a65b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Zones']/parent::*</value>
      <webElementGuid>58065cf5-bc34-4384-916b-08f1c94b3579</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[36]/a/p</value>
      <webElementGuid>4614e113-7c67-4364-b8d7-3ac8c67d6deb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@title = 'Zones' and (text() = 'Zones' or . = 'Zones')]</value>
      <webElementGuid>884faffd-cc8e-4810-bf20-ca77f30bbf8d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
