<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>error_msg_single</name>
   <tag></tag>
   <elementGuidId>0fe21a88-0c49-41b0-aa0b-9a9ed05e5988</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.invalid-feedback</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
