<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>field_number_filled</name>
   <tag></tag>
   <elementGuidId>114fc902-30b3-4017-aaa0-a99fb16b70f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[name='loyalty_number']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
