<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>modal_content_edit</name>
   <tag></tag>
   <elementGuidId>3e4c1021-2804-4eca-85c4-5642df1b190f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.modal-content</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
