<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pagination_control</name>
   <tag></tag>
   <elementGuidId>87e96000-6dc9-462b-bdb7-e1d398ceb82f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.pagination</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
