<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>save_btn_dialog</name>
   <tag></tag>
   <elementGuidId>e674bede-8aec-48dd-b407-f039ccf6afff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[.='SAVE'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.btn-blue-dark-custom</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
