<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Occupancy Type</name>
   <tag></tag>
   <elementGuidId>ade33cbf-ba03-4bab-ae42-1a0120538405</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='menu-occupancy-type']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-occupancy-type</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ef11d6d9-5d5b-4c19-a137-423ad362c609</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menu-occupancy-type</value>
      <webElementGuid>76683d3f-e0d1-421e-ab61-100a48f0a793</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link active-link</value>
      <webElementGuid>648dcbf6-477d-471a-a83a-6ac778d58481</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/master/occupancy-types</value>
      <webElementGuid>8c76d189-6e6f-44d5-b50a-b8f39b49bc6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Occupancy Type</value>
      <webElementGuid>9c5dadee-f8ad-4a5b-91d9-38ba63d494a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-occupancy-type&quot;)</value>
      <webElementGuid>e05adb7a-7b8d-4ee6-9e43-e1dbcf4aaedd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='menu-occupancy-type']</value>
      <webElementGuid>e1de230e-355e-4e8c-b280-660f36b751ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='d14be77b-679e-5f33-aab7-f6719e54180a']/ul/li[22]/a</value>
      <webElementGuid>a38d13c5-9193-458d-98d7-c15a22d37b13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Out'])[1]/following::a[24]</value>
      <webElementGuid>69ded59b-4484-483f-b191-0d209dc230a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change Password'])[1]/following::a[24]</value>
      <webElementGuid>1ea10b77-cdb5-4fac-852f-4bea29a0a450</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Master Data Management'])[2]/preceding::a[40]</value>
      <webElementGuid>7774f8ad-a83f-4176-9238-2f217af3526e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Occupancy Types'])[1]/preceding::a[40]</value>
      <webElementGuid>663d817c-acd6-407a-a4c5-64aa37080b4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/master/occupancy-types')]</value>
      <webElementGuid>e0019b53-af10-458b-a2cf-fa0ee3cfc5de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[22]/a</value>
      <webElementGuid>c87688ca-18e2-4e2a-9451-905548e0bd93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'menu-occupancy-type' and @href = '/master/occupancy-types' and (text() = 'Occupancy Type' or . = 'Occupancy Type')]</value>
      <webElementGuid>d4a1f01d-5b73-4b05-9036-7ae71271c2c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
