<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icon_details</name>
   <tag></tag>
   <elementGuidId>811cf2eb-b18e-48ec-af1c-243c3c46551a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='table-0']/td[7]/a[3]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.d-inline.table-row-action-item > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4f4cc1fe-ffa7-41a5-845a-48ab645811b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/media/show.8a72077a.svg</value>
      <webElementGuid>0ec517e1-f499-4461-8871-c91824efd597</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table-0&quot;)/td[@class=&quot;desktop&quot;]/a[@class=&quot;d-inline table-row-action-item&quot;]/img[1]</value>
      <webElementGuid>007df753-80ee-4343-9ecd-596eaba43fc8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='table-0']/td[7]/a[3]/img</value>
      <webElementGuid>3d7cc62b-5302-4856-bc50-7c97a4a79d00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]/img</value>
      <webElementGuid>9006fa42-2a99-431e-b64b-2a7c0fd3d3e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/static/media/show.8a72077a.svg']</value>
      <webElementGuid>61ca0d13-8f62-4c4c-b197-88b009d08132</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
