<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>row_table</name>
   <tag></tag>
   <elementGuidId>121fc64f-4dbc-4d1a-9632-74cc504073eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.custom-select</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
