<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Create New_datatable-download</name>
   <tag></tag>
   <elementGuidId>861e16bb-08cf-424f-adc1-08e820edf926</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#datatable-download</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='datatable-download']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a76ba85f-7321-4773-93d4-2de2c467b89c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/media/download.a55d3bc6.svg</value>
      <webElementGuid>a94d2bf9-94b3-46c3-93cb-65f723da13e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-circle</value>
      <webElementGuid>2cc0f8a3-9f4c-4692-8d92-786b2bc065b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>download</value>
      <webElementGuid>83a0c2c1-f8e3-438c-b4a7-186a6b4b943e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>datatable-download</value>
      <webElementGuid>3fe77197-1370-431d-8ab8-ffca301ba097</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;datatable-download&quot;)</value>
      <webElementGuid>d674daf5-a4d9-4bdb-9c07-a357dc422256</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='datatable-download']</value>
      <webElementGuid>9d735715-ccc4-40cb-b906-aad2789d9bde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/section/div/div/div/div/div[3]/a[2]/img</value>
      <webElementGuid>a75130ea-0374-4d48-967d-72060e73be4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='download']</value>
      <webElementGuid>d6c10a64-b8c2-420b-80cf-a651852251a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/img</value>
      <webElementGuid>2f1a0a7e-8e73-4eba-af5b-690eddd6c64a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/static/media/download.a55d3bc6.svg' and @alt = 'download' and @id = 'datatable-download']</value>
      <webElementGuid>2d0fbb17-29ac-41a4-9ad6-75edd6f640aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
