<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_draftinactive_custom-control-label</name>
   <tag></tag>
   <elementGuidId>d7ee5ebd-f2ef-49b8-9405-3d909b5ab8d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='DataTables_Table_0']/tbody/tr[5]/td[6]/a[4]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>560f4fc2-598d-433a-a844-aee46ccc2d24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-control-label</value>
      <webElementGuid>b8de7065-5d80-4a2b-b905-75760d879c6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>customSwitch0131463b-3471-492a-b731-2184751ae523</value>
      <webElementGuid>2bbe6e63-7bdb-4d62-8758-ce410dcbdc93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action</name>
      <type>Main</type>
      <value>update_status</value>
      <webElementGuid>b4de8be9-6efd-46c3-a0cf-9dddc4b11533</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DataTables_Table_0&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[6]/a[@class=&quot;d-inline-block custom-switch custom-switch-bb table-row-action-item&quot;]/label[@class=&quot;custom-control-label&quot;]</value>
      <webElementGuid>35627680-a9ce-4938-8b51-b9a39ad7e6ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='DataTables_Table_0']/tbody/tr[5]/td[6]/a[4]/label</value>
      <webElementGuid>191b0df6-e78d-4312-9671-464614eb4f52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[6]/a[4]/label</value>
      <webElementGuid>fd8bb74d-9252-4821-b5c8-2bfd63688741</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
