<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>breadcrumb</name>
   <tag></tag>
   <elementGuidId>f6e96549-e1e6-4b47-9eb7-7708c27b2472</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.breadcrumb</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
