<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dashboardBtn</name>
   <tag></tag>
   <elementGuidId>6a6a61e2-1d17-4a35-86be-da43b7d63429</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[.='Dashboard']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
