<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>breadcrumb</name>
   <tag></tag>
   <elementGuidId>ad15589c-b6be-4c16-bb81-a7484051cc72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.breadcrumb</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
