<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnPrint</name>
   <tag></tag>
   <elementGuidId>fb1238f3-b660-4e71-83a4-365358e85b02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[alt='print']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
