<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dataTableAppears</name>
   <tag></tag>
   <elementGuidId>f34d2961-e5a5-48f3-ba96-5acfa7f86573</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.dataTable-root</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
