<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>downloadBtn</name>
   <tag></tag>
   <elementGuidId>ab48bfa1-3de4-4053-9463-ad8e014f1e9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#datatable-download</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
