<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>filterAutomation</name>
   <tag></tag>
   <elementGuidId>70b5c6c7-a7f7-41b1-8e7a-5719bee93c8e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.select2-results__option--highlighted</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
