<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mainHeaderTitle</name>
   <tag></tag>
   <elementGuidId>c5fa95c6-12f7-4ba5-8838-23c92bc46e30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.main-header-title</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
