<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>nextPage</name>
   <tag></tag>
   <elementGuidId>bd0b1e2f-5e75-4f62-9f0c-b6191d1a78fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[data-dt-idx='3']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
