<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>paginationRow</name>
   <tag></tag>
   <elementGuidId>c6d3d473-daa4-4a7c-a95d-230f8a629962</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.pagination</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
