<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>popUpCancelDelete</name>
   <tag></tag>
   <elementGuidId>1c2a1a5d-a696-4ccb-a6d9-ee08470dc642</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.btn-secondary</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
