<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>popUpDeleteButton</name>
   <tag></tag>
   <elementGuidId>46af11d4-fe0d-4e76-b6cf-b1c3281eac3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.btn-danger</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
