<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>stateActive</name>
   <tag></tag>
   <elementGuidId>aded5f40-6ee5-4ed1-a096-8d33111358c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[.='Active']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
