<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>titlePagination</name>
   <tag></tag>
   <elementGuidId>c3aee500-4bdc-454f-9d07-0f4eae5e035c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.text-label-input-paginate</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
