<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>toggleBtn</name>
   <tag></tag>
   <elementGuidId>a2d86003-bc1e-484f-bd7c-e73ab2599e9b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>//tr[3]//a[4]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[3]//a[4]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
