<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Email_img-fluid</name>
   <tag></tag>
   <elementGuidId>122462da-42f0-436b-abc4-7801961e53fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.img-fluid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>62299ffd-e9e7-44a7-b1e2-1dc29d330702</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://bbstg.monstercode.net/files/0feee8c7-cba8-41b3-ab4d-5e2c3dac55c4.png</value>
      <webElementGuid>4c1acd60-8601-4dee-a8db-2a07a45e4e39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-fluid</value>
      <webElementGuid>5e8832e9-3e58-4510-a6e8-385c79b69612</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;auth-page&quot;]/div[@class=&quot;auth-wrapper&quot;]/div[@class=&quot;card-image&quot;]/img[@class=&quot;img-fluid&quot;]</value>
      <webElementGuid>c2d44c14-2134-441b-af96-0543a82faf8d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/img</value>
      <webElementGuid>ec5ce3d6-3c4c-4f89-952d-da7d21dce9f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://bbstg.monstercode.net/files/0feee8c7-cba8-41b3-ab4d-5e2c3dac55c4.png')]</value>
      <webElementGuid>d5671a3c-37f7-4574-b9fa-413ae5716c0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>9fac9fff-b14e-4820-9c75-10296d2d8145</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://bbstg.monstercode.net/files/0feee8c7-cba8-41b3-ab4d-5e2c3dac55c4.png']</value>
      <webElementGuid>185f023e-bd1f-4cbb-a69f-b37521dcea0f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
