<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_SIGN IN_bb-logo d-none d-md-block</name>
   <tag></tag>
   <elementGuidId>a6d63b0f-c5ee-48a2-a63d-0055eb8e17b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.bb-logo.d-none.d-md-block</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/div[3]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>608a739e-dcf9-4da7-bf73-99f675774c1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/img/logo.png</value>
      <webElementGuid>60bd6c25-8cdf-4621-8a39-ba2b72269fcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bb-logo d-none d-md-block</value>
      <webElementGuid>767f5ba4-e805-4617-83cb-17aab2ef9de4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>logo</value>
      <webElementGuid>18d7115f-ac12-471b-a2ee-7e463b4f36fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;auth-page&quot;]/div[@class=&quot;auth-wrapper&quot;]/div[@class=&quot;card-form&quot;]/div[@class=&quot;card-form-footer position-absolute pb-4&quot;]/img[@class=&quot;bb-logo d-none d-md-block&quot;]</value>
      <webElementGuid>cc3c0e1c-631c-43fa-a47c-15f7d60d374f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div[3]/img</value>
      <webElementGuid>40ba5ead-ef89-48e7-a29f-e73648682cd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='logo']</value>
      <webElementGuid>58843f24-fbaf-4500-a59a-6cb9453c3c2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/img</value>
      <webElementGuid>bb2a685c-163d-46e2-ac96-f7bafd888550</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/img/logo.png' and @alt = 'logo']</value>
      <webElementGuid>c540eb62-a604-474b-859f-e42896aca32d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
