<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_custom-inline-checkbox-remember</name>
   <tag></tag>
   <elementGuidId>1c5fb587-b210-4a1f-bc4d-0f834d8799f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#custom-inline-checkbox-remember</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='custom-inline-checkbox-remember']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e19ac074-0db6-43cf-8456-6ce63cf57b4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>a2c60e7d-228b-4bce-b912-20e8a07a0485</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>custom-inline-checkbox-remember</value>
      <webElementGuid>7a456b61-3b4d-46c6-bb62-2f5c8d872f63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>a5a5e741-5104-489b-a530-9ddfc936005c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;custom-inline-checkbox-remember&quot;)</value>
      <webElementGuid>97f6a931-eb43-46a6-bc3c-061159e3195a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='custom-inline-checkbox-remember']</value>
      <webElementGuid>e85ab8fd-ab70-4e77-a385-66757473b91f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div[2]/div/form/div[3]/div/div/input</value>
      <webElementGuid>1f7a8402-82bd-4071-be45-0305acfc5157</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>92f11766-d995-4ecb-bba7-8fa3575e5b87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'custom-inline-checkbox-remember']</value>
      <webElementGuid>b78d8e9a-10da-44a0-8817-db1570bd9071</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
