<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Dashboard</name>
   <tag></tag>
   <elementGuidId>7bdde71b-5256-41c3-8735-1530fe089275</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.caption</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/p</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>(//*[(text()='Dashboard')])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>b0f4900c-9598-4f9a-b522-b31ae1683605</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>caption</value>
      <webElementGuid>795dc904-9ae8-4e79-ae6d-31757c019959</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>We are, The Expert Travel Agent Partnership</value>
      <webElementGuid>b2f86a8d-f11a-408e-979c-13fba96c748d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//*[(text()='Dashboard')])[2]</value>
      <webElementGuid>cf972e8d-e475-4241-aac2-a338a8937946</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/p</value>
      <webElementGuid>2788a40b-6776-42fc-9a99-e02eab2fb16e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/preceding::p[4]</value>
      <webElementGuid>7c251357-feff-48ed-a8ab-d8c9df3f1f05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/preceding::p[4]</value>
      <webElementGuid>fb068e65-76e7-4dbb-8bac-9d23efd7df65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='We are,']/parent::*</value>
      <webElementGuid>75db7a8e-6cbf-4d58-a583-701b3f7cb0df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>988910c1-9c16-4b22-9a8b-257f6a763219</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'We are, The Expert Travel Agent Partnership' or . = 'We are, The Expert Travel Agent Partnership')]</value>
      <webElementGuid>38d83959-8736-4545-a4a5-80770449ae34</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
