<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Age Qualifying Type Name_age_qualifyi_ba4776</name>
   <tag></tag>
   <elementGuidId>f30d4998-81da-4f10-ac28-f87ee8c1a196</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;age_qualifying_type_name&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='age_qualifying_type_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c51ad075-2498-4970-ae50-5cc451bd6445</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>9c90930c-c058-48f8-8972-b92b4c349426</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>Age Qualifying Type Name</value>
      <webElementGuid>8e4bcd55-d252-4dba-82ee-c956832b4964</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>age_qualifying_type_name</value>
      <webElementGuid>8da8c3c3-5971-4946-9ba3-76235cd53f7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a08f7fb6-19f1-494f-aa92-274447b07eb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>6755e95b-bb86-45e5-adc8-de7dfa9b8b04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>256</value>
      <webElementGuid>f928418b-61f4-41c3-9933-98236712e962</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;content-wrapper&quot;]/div[@class=&quot;container-fluid pb-5&quot;]/section[@class=&quot;content&quot;]/form[@class=&quot;container-fluid pl-0&quot;]/div[@class=&quot;card card-default border&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12 col-sm-6 col-md-7 col-lg-6 order-2 order-sm-1 mb-4&quot;]/div[@class=&quot;form-horizontal&quot;]/div[@class=&quot;form-group required row d-flex align-items-center&quot;]/div[@class=&quot;form-control-wrapper col-sm-6 col-md-7 col-lg-8&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>09aec5d9-49cf-476f-8f23-5b1fe9a157e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='age_qualifying_type_name']</value>
      <webElementGuid>722724be-9c57-4105-9e16-2928c35eae34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/section/form/div/div/div/div/div/div/div[2]/input</value>
      <webElementGuid>b365facb-9e60-4810-8747-765f30fe9b76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>d1161789-8ef1-4a35-ab0b-24a3f37d7946</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'age_qualifying_type_name' and @type = 'text']</value>
      <webElementGuid>d517c058-045b-4872-8cdd-a378167795ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
