<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Age Qualifying Type Code_age_qualifyi_5ae899</name>
   <tag></tag>
   <elementGuidId>fd8daa84-24c8-4ec1-b23c-3869d5c035df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;age_qualifying_type_code&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='age_qualifying_type_code']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d0af0998-6e1e-42df-9938-614e5c5864a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control is-invalid</value>
      <webElementGuid>27b691ff-5894-404f-80b7-0424ab0e82c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>Age Qualifying Type Code</value>
      <webElementGuid>96e96642-4e7d-40a8-a23d-242e5dd98ff6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>age_qualifying_type_code</value>
      <webElementGuid>a151957e-aefd-4482-95d2-fa219a861f2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cl</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>9c51ef1b-c3d3-45e9-8f82-0c5578d9358d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cr</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>fb9438e5-b497-49a6-9da9-b830aa5ec7cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>90cb7771-ef82-4bda-b2f5-b34bad574924</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>age_qualifying_type_code-error</value>
      <webElementGuid>c4cb5b15-8237-4031-840e-f6e4570bc9e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>57b6977d-3375-47a0-af59-f4569cf329c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;content-wrapper&quot;]/div[@class=&quot;container-fluid pb-5&quot;]/section[@class=&quot;content&quot;]/form[@class=&quot;container-fluid pl-0&quot;]/div[@class=&quot;card card-default border&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12 col-sm-6 col-md-5 col-lg-5 order-1 order-sm-2&quot;]/div[@class=&quot;card card-default shadow-none border-none bg-block-card&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;form-horizontal&quot;]/div[@class=&quot;form-group required row d-flex align-items-center&quot;]/div[@class=&quot;form-control-wrapper col-sm-6 col-md-undefined col-lg-undefined&quot;]/input[@class=&quot;form-control is-invalid&quot;]</value>
      <webElementGuid>cdf33874-6181-46b6-bb3d-bcb66a5189ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='age_qualifying_type_code']</value>
      <webElementGuid>5f02ec5e-b2c5-47bd-88e6-bddd67fe21e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/section/form/div/div/div/div[3]/div/div/div[2]/div/div[2]/input</value>
      <webElementGuid>239a866b-f3cc-48c0-b5fe-d83fd4cf54fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/input</value>
      <webElementGuid>ac68e6e3-09c5-4d8c-8369-2ce12881b989</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'age_qualifying_type_code' and @type = 'number']</value>
      <webElementGuid>b7a8c9b7-9967-4c68-b133-68f5562eb1e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
