<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>main-header-title</name>
   <tag></tag>
   <elementGuidId>c81527db-79bb-46c7-90d0-8e416c507e91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'main-header-title' and (text() = 'Languages' or . = 'Languages')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>main-header-title</value>
      <webElementGuid>250763f3-3ebd-4f36-a66f-54a3414fbc32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Languages</value>
      <webElementGuid>a3b5a040-a62d-4835-ba5a-ac0767f9b677</webElementGuid>
   </webElementProperties>
</WebElementEntity>
