<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Destination</name>
   <tag></tag>
   <elementGuidId>719660ac-8d94-436d-9775-9c5cf50dcf7c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div[1]/div/div[1]/section/form/div[1]/div/div[1]/div[1]/div/div[2]/div[2]/span/span[1]/span/span[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
