<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tableHeader_Status</name>
   <tag></tag>
   <elementGuidId>6464f80a-2bbf-41a1-9979-ed139aeaca43</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@aria-controls = 'DataTables_Table_0' and @data-column-index = '4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>DataTables_Table_0</value>
      <webElementGuid>d74f5581-13b5-4c3e-8660-c691079ced7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-column-index</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>81ba71ac-3aa7-49f5-bbfc-02870026a0f0</webElementGuid>
   </webElementProperties>
</WebElementEntity>
