<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>toggleBtn</name>
   <tag></tag>
   <elementGuidId>a9b89031-9067-4dae-be1b-dc36c52dbe0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[3]//a[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>//tr[3]//a[4]</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
