<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>field_occ type code</name>
   <tag></tag>
   <elementGuidId>dd6661fc-78f5-4c18-806b-4b3a0a21ef39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='occupancy_type_code']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#occupancy_type_code</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8725dff4-fcec-4da6-bd35-1c4b05cb3458</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>08852fea-ee31-4454-ba3c-54a9b2dc1280</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>Occupancy Type Code</value>
      <webElementGuid>444ecffb-e60b-4c31-acb4-34962636e8a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>occupancy_type_code</value>
      <webElementGuid>e8363b48-ac27-4618-a306-e3bb5209825c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>occupancy_type_code</value>
      <webElementGuid>8b2d7395-6430-4db8-a8bd-538d7e5fc909</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cl</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>81d53e8e-9eca-41e4-9e87-19f2a361c984</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cr</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>9f0fc644-35e5-4a98-9685-3f40bf445e5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d453dfca-d732-4f25-809f-1fc884e8464d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>7d3df9eb-4a62-4eca-b1e1-18c242db0732</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>36</value>
      <webElementGuid>4b6ff6c9-b173-4c32-9263-5f01bc22b5a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>hint</name>
      <type>Main</type>
      <value>The code of the occupancy type, e.g. single, double.</value>
      <webElementGuid>a69bc627-2cff-47d0-bab1-36c332824531</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>tesupdatemandatory</value>
      <webElementGuid>2f7860d8-6249-43e1-9b53-962294794c77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;occupancy_type_code&quot;)</value>
      <webElementGuid>7e72f1af-99a2-4a62-8cff-af6fabea5513</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='occupancy_type_code']</value>
      <webElementGuid>59ee64d9-cb5d-42fd-b7f0-a73ef9f30134</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/section/form/div/div/div/div[3]/div/div/div[2]/div/div[2]/input</value>
      <webElementGuid>3c4f1b48-7aed-4c29-8456-74caf8a6cec1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div/div[2]/input</value>
      <webElementGuid>d028aca5-fd9d-4971-9a5d-c6cf5ed55b57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'occupancy_type_code' and @id = 'occupancy_type_code' and @type = 'text']</value>
      <webElementGuid>34ee6231-26cf-448f-8abc-2c66734e3570</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
