<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>field_occ type name</name>
   <tag></tag>
   <elementGuidId>f6bc8859-bf21-43bb-af48-c17928878d82</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='occupancy_type_name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#occupancy_type_name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b3c5b65e-7e90-4237-b211-368ab020a758</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c4dfcba6-7707-4f76-9ba3-06ad0d9b5ab8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>Occupancy Type Name</value>
      <webElementGuid>54c3d4b5-81c4-404c-80f2-839a624ec7d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>occupancy_type_name</value>
      <webElementGuid>a3bad81d-96ee-49db-8895-97e7e2de3683</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>occupancy_type_name</value>
      <webElementGuid>7864fb35-463c-49bb-8e05-8a42987fab59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b355e306-0f74-4b81-8c80-6bc40e9f6aca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a3ad595a-b3f8-44ec-985b-6d36018f32fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>256</value>
      <webElementGuid>367e5ee0-0b64-475a-a3ee-06239d8e2a7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>tesupdatemandatory</value>
      <webElementGuid>3c1fdf53-c358-443d-926a-9e8b39f5b3be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;occupancy_type_name&quot;)</value>
      <webElementGuid>5b2d1990-07be-42c6-976b-9fb4549fa013</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='occupancy_type_name']</value>
      <webElementGuid>520cbd00-d6dd-44b7-b5dc-4f1196f24d8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/section/form/div/div/div/div/div/div/div[2]/input</value>
      <webElementGuid>4f89376c-2e4c-4fce-95b2-2ec606f94b00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>4a65d3e6-aa21-47cd-9b2b-32b13f45fcd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'occupancy_type_name' and @id = 'occupancy_type_name' and @type = 'text']</value>
      <webElementGuid>171a3dce-128b-4711-8ab5-b7486ece2e32</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
