<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Edit_alert_Occupancy Type Name already exists</name>
   <tag></tag>
   <elementGuidId>6c3584e1-0f8b-4fb7-ba52-1da30ab95d0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='occupancy_type_name-error']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#occupancy_type_name-error</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>005c747e-4265-4d32-94b6-9ef663413b16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>occupancy_type_name-error</value>
      <webElementGuid>1baefbbf-8603-47bf-a4ef-d1da935f6a29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>error invalid-feedback</value>
      <webElementGuid>7c2712bf-d574-4c71-831b-9559414b12f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Occupancy Type Name already exists</value>
      <webElementGuid>65cce3a0-5050-4660-97fa-429b71f14df8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;occupancy_type_name-error&quot;)</value>
      <webElementGuid>1262d285-33c9-43e8-a758-a5fbcaf1a464</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='occupancy_type_name-error']</value>
      <webElementGuid>9367e379-23c2-4e97-8c88-53f905b3fb24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/section/form/div/div/div/div/div/div/div[2]/span</value>
      <webElementGuid>f2ba75f6-c06e-4015-8a53-9ca2807e32a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Occupancy Type Name'])[1]/following::span[1]</value>
      <webElementGuid>d4715442-b9d1-4c01-a784-7281f5d487bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit Occupancy Type'])[2]/following::span[2]</value>
      <webElementGuid>cf706a43-e928-4222-bb73-1b770001c459</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Is Default'])[1]/preceding::span[1]</value>
      <webElementGuid>e3c8f8e7-562e-4b88-9420-098f326016d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[1]/preceding::span[2]</value>
      <webElementGuid>64b56f52-d26c-4028-b3e1-8aba982493ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Occupancy Type Name already exists']/parent::*</value>
      <webElementGuid>0b72ea0b-cc12-4f20-8bc1-c564856590ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div[2]/span</value>
      <webElementGuid>5cb566d8-fe7a-4751-8421-dcb5ff599dcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'occupancy_type_name-error' and (text() = 'Occupancy Type Name already exists' or . = 'Occupancy Type Name already exists')]</value>
      <webElementGuid>17e8794b-c8f6-4d68-84ea-afe4e511e5e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
