<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Actions_float-left select-checkbox-it_8952ca</name>
   <tag></tag>
   <elementGuidId>f276e499-a193-4cbd-9460-c08886816007</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.float-left.select-checkbox-item.ml-2.mr-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='checkbox'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dc43e287-8973-4126-8681-9bc5a54eaa8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>85ca8a86-75e7-4a17-96c8-23e78021e262</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>217cfe27-ca79-4a7f-89af-6f9a82fbbbbf</value>
      <webElementGuid>5a6a215e-92e0-4a2f-9dec-cac5a9678694</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>float-left select-checkbox-item ml-2 mr-1</value>
      <webElementGuid>90576e52-6498-4f7e-baaa-8be5fced8f04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DataTables_Table_0&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;select-checkbox dtr-control&quot;]/input[@class=&quot;float-left select-checkbox-item ml-2 mr-1&quot;]</value>
      <webElementGuid>db21ba76-9b1e-49b8-88b2-bdbd6617a367</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='checkbox'])[2]</value>
      <webElementGuid>15ab0f54-8efd-4ee6-9085-dffe9e3b5a84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='DataTables_Table_0']/tbody/tr/td/input</value>
      <webElementGuid>ae12db98-34f2-43ec-a393-5e654ce7ee74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>b720ce8f-893f-43cd-a846-c0cef7635784</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>f0f377aa-de71-4573-9fbf-668b24ca2823</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
