<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>path_Actions_svg_2</name>
   <tag></tag>
   <elementGuidId>74752136-2ddd-4a20-90f8-56145af8c179</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//path[@id = 'svg_2']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>(//*[@id = 'svg_2'])[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#svg_2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>path</value>
      <webElementGuid>bc2fd369-38d6-42e6-b092-29c7c8e0c863</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>d</name>
      <type>Main</type>
      <value>M11.901639938354492,13 a1.5,1.5 0 1 1 -3,0 a1.5,1.5 0 0 1 3,0 zm0,-5 a1.5,1.5 0 1 1 -3,0 a1.5,1.5 0 0 1 3,0 zm0,-5 a1.5,1.5 0 1 1 -3,0 a1.5,1.5 0 0 1 3,0 z</value>
      <webElementGuid>01900e34-3b27-4947-afc6-6181dd0a56fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>#707070</value>
      <webElementGuid>61def458-5edd-4261-acb2-9a8a1dca5dec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>svg_2</value>
      <webElementGuid>e0dd8aad-fcb3-4e84-a441-12b620f4c75c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//*[@id = 'svg_2'])[1]</value>
      <webElementGuid>fcf70bfc-58af-451d-9588-2fe9e5d39587</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//path[@id = 'svg_2']</value>
      <webElementGuid>c1da5c7a-4ca2-4729-91f9-1e790e38725b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
