<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Create New_datatable-download</name>
   <tag></tag>
   <elementGuidId>01c152ab-b057-4234-9005-3925e79159fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#datatable-download</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='datatable-download']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9128c964-8188-4259-ba08-a6474de8f445</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/media/download.a55d3bc6.svg</value>
      <webElementGuid>6bf1c748-b6f1-4e83-9c70-6b206183a380</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-circle</value>
      <webElementGuid>74aa6deb-f321-4234-a12d-62a9a6ac0665</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>download</value>
      <webElementGuid>3349a4f9-70b9-4fcd-9126-a46bbf8f3eed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>datatable-download</value>
      <webElementGuid>005c5beb-345b-4510-8cfe-df3947a779cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;datatable-download&quot;)</value>
      <webElementGuid>e170345e-1e15-4f7f-864d-0c4100baab98</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='datatable-download']</value>
      <webElementGuid>0c93e9e3-7042-4329-8308-3cca60a5731c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/section/div/div/div/div/div[3]/a[2]/img</value>
      <webElementGuid>68b37cbd-2b37-4360-9aae-9a3c6e7e6953</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='download']</value>
      <webElementGuid>55e02082-b7fb-48cf-8829-70a5eebb0e4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/img</value>
      <webElementGuid>f69de29d-a11d-4dad-8cef-a5cd5ec6d55d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/static/media/download.a55d3bc6.svg' and @alt = 'download' and @id = 'datatable-download']</value>
      <webElementGuid>0b9d3534-e354-459d-9c43-1e907a084c3a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
