<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Actions_float-left select-checkbox-it_8952ca</name>
   <tag></tag>
   <elementGuidId>f462e8b7-7541-4020-9805-46c75a39b6bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.float-left.select-checkbox-item.ml-2.mr-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='checkbox'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>13870e3f-c519-4eb6-aa74-2ea9dcf6f635</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>333b96d5-8cf2-4c6f-bdcd-3742ca8bb548</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>4944bda3-0c6e-4626-8184-20f1c12643e3</value>
      <webElementGuid>0b754948-3b3b-4f23-b32e-0c3555085bde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>float-left select-checkbox-item ml-2 mr-1</value>
      <webElementGuid>b2adf6ba-8ad1-4abf-a8ac-12cc91cd2696</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DataTables_Table_0&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;select-checkbox dtr-control&quot;]/input[@class=&quot;float-left select-checkbox-item ml-2 mr-1&quot;]</value>
      <webElementGuid>ffeb9fef-6ae5-4bdf-9179-38d7d20db6b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='checkbox'])[2]</value>
      <webElementGuid>b86c6b99-91dd-4ff3-a6d1-660dfa69230f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='DataTables_Table_0']/tbody/tr/td/input</value>
      <webElementGuid>17788ba0-b3c2-4a4b-a383-740e3e6026b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>d73f1318-678e-4f36-bc81-f91ddf600368</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>0a954d52-65ef-4e8d-a797-1fa0a1136d62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
