<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_REMOVE AIRCRAFTS_cb-th</name>
   <tag></tag>
   <elementGuidId>fabaaa30-fe02-40a1-8f44-f97a2dd0865a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cb-th</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cb-th']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a33c2ff5-700a-4c96-bf88-8b291540c56f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>55af123c-77b7-475f-93bb-c23bdd3765af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cb-th</value>
      <webElementGuid>acb2668b-096c-4db8-956a-ad21ca71ac38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-checkbox-all ml-2 mr-1</value>
      <webElementGuid>513354a4-df5a-4616-b4a9-f1591dec208b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cb-th&quot;)</value>
      <webElementGuid>4683db7b-c020-496c-86b3-dda071a8279c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cb-th']</value>
      <webElementGuid>82c40404-7bb9-4c2b-8a81-971ec42efa1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='DataTables_Table_0']/thead/tr/th/input</value>
      <webElementGuid>263cd953-277d-4cfb-9914-773594e57e84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th/input</value>
      <webElementGuid>838005dd-4c13-4f08-828e-950bf8e7fa36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'cb-th']</value>
      <webElementGuid>ea6e02c1-9918-4a0e-9c64-3f8cd21d3b89</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
