<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Status</name>
   <tag></tag>
   <elementGuidId>3c1ffd39-5bce-401f-8e1a-7e45aeeb3789</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.text-label-filter.ml-2.font-weight-bold</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/section/div/div/div/div[2]/div/div/div/div/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>3dfc469a-c848-4041-8c19-3104ce2a3c2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-label-filter ml-2 font-weight-bold</value>
      <webElementGuid>3dd76389-a832-4c5e-aaca-5fb82004a4c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Status</value>
      <webElementGuid>2a9d64ba-1ab9-416e-8793-fd8a2bcf8f4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;content-wrapper&quot;]/div[@class=&quot;container-fluid pb-5&quot;]/section[@class=&quot;content&quot;]/div[@class=&quot;dtBIcony&quot;]/div[1]/div[@class=&quot;container-fluid pl-0&quot;]/div[@class=&quot;card card-default advanced-filter shadow-none my-2&quot;]/div[@class=&quot;card-body-filter&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12 col-sm-12 col-md-6 col-lg-3 filter-fixer-corp-user-mgmnt&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-4&quot;]/label[@class=&quot;text-label-filter ml-2 font-weight-bold&quot;]</value>
      <webElementGuid>08747c6c-9b0d-429f-858a-b2b6832dab84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/section/div/div/div/div[2]/div/div/div/div/div/label</value>
      <webElementGuid>d7f99a1c-574f-4b13-85f0-30744e616e87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create New'])[1]/following::label[1]</value>
      <webElementGuid>e29a5c02-072d-4f9c-a3da-8b369309fd48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Advanced Options'])[1]/following::label[1]</value>
      <webElementGuid>4e87a98b-5332-4d14-ae5e-c504a2fd5b10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All'])[1]/preceding::label[1]</value>
      <webElementGuid>29c7cd47-90bb-41c5-9b65-09d1c566cf1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UPDATE STATUS'])[1]/preceding::label[1]</value>
      <webElementGuid>25d59e2c-10a4-468d-88d2-ad92f063c74e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Status']/parent::*</value>
      <webElementGuid>e08bd1de-8771-4de2-9543-24ce59bd8d89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>09ed9ac2-73c0-4ebc-a5e0-469b926cdc10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Status' or . = 'Status')]</value>
      <webElementGuid>0bd5bb1a-0b88-4135-bb6a-77d72de68fff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
