<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Aircrafts</name>
   <tag></tag>
   <elementGuidId>871cfae7-9d99-4efc-8195-56e230837dfe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.breadcrumb-overflow.breadcrumb-item.active</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div/div/div/div/div/ol/li[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>63268ae7-417e-44bf-9e3c-e15ae2fea296</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>breadcrumb-overflow breadcrumb-item active</value>
      <webElementGuid>c6505e05-082d-4108-9e4d-9505791cf23d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Aircrafts</value>
      <webElementGuid>9fd364ee-8d76-4e9f-b3af-2f55fb5132bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;content-wrapper&quot;]/div[@class=&quot;container-fluid pb-5&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col&quot;]/div[@class=&quot;content-header&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xl-8 col-lg-6 col-sm-6&quot;]/div[@class=&quot;mb-2 m-hm-0&quot;]/ol[@class=&quot;breadcrumb&quot;]/li[@class=&quot;breadcrumb-overflow breadcrumb-item active&quot;]</value>
      <webElementGuid>f3858829-0d53-4e26-86a6-bf3fef93e210</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div/div/div/div/ol/li[2]</value>
      <webElementGuid>76efbc15-ee40-4f9a-ae83-a6d4c759fee6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Master Data Management'])[2]/following::li[1]</value>
      <webElementGuid>252deea2-8c04-413a-939b-b9934be0f1ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IDR'])[1]/following::li[65]</value>
      <webElementGuid>87cb9758-cd64-4e9c-b7fa-080366ff4965</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aircrafts'])[2]/preceding::li[1]</value>
      <webElementGuid>d5806cb1-7bbb-4ccd-b461-5eb94c4edcec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Advanced Options'])[1]/preceding::li[1]</value>
      <webElementGuid>62c2eda6-0d9d-4000-b223-0b05e1790e5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Aircrafts']/parent::*</value>
      <webElementGuid>51318759-d5ce-497a-b71f-cd95bc0564bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ol/li[2]</value>
      <webElementGuid>c8f3f669-ed2b-47f4-a4e2-096c9ceb70af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Aircrafts' or . = 'Aircrafts')]</value>
      <webElementGuid>59f61834-de99-4440-929a-00fe92c915da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
