<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_102550100All</name>
   <tag></tag>
   <elementGuidId>6263d58d-4fe0-4980-8049-dab354dd7adb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;DataTables_Table_0_length&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='DataTables_Table_0_length']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>673e0414-9982-4e1d-873c-c40e07a0676e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DataTables_Table_0_length</value>
      <webElementGuid>753f931c-1445-4ad7-818d-547f63a859e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>DataTables_Table_0</value>
      <webElementGuid>2cd6fead-a535-45f7-938a-42694213171b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-select custom-select-sm form-control form-control-sm</value>
      <webElementGuid>ecc6e41e-2370-465a-a0a9-2d3c09af1bb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>102550100All</value>
      <webElementGuid>4804b3ef-d4ca-4c3c-a626-1d2cfc8fbab3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DataTables_Table_0_length&quot;)/label[1]/select[@class=&quot;custom-select custom-select-sm form-control form-control-sm&quot;]</value>
      <webElementGuid>804c0126-7a31-4894-96f8-589b8a95833d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='DataTables_Table_0_length']</value>
      <webElementGuid>8623aa81-857b-4d91-a764-1e183396efed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DataTables_Table_0_length']/label/select</value>
      <webElementGuid>f5d10489-ca31-4377-b53d-43a3d5dca84a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[1]/following::select[1]</value>
      <webElementGuid>a139b77e-90dd-4ede-aedd-2a6d631a6ab1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[11]/following::select[1]</value>
      <webElementGuid>edc723f8-ae95-42a1-a735-d04acf513b15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Showing 1 - 10 of 263'])[1]/preceding::select[1]</value>
      <webElementGuid>2353d6f1-37d0-4e4a-9117-0e5adf9ea5ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Page:'])[1]/preceding::select[1]</value>
      <webElementGuid>7cc9697b-d51b-435b-a229-75199a403579</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>7239bdc7-61c1-4b70-8e7a-0207b3f48a74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'DataTables_Table_0_length' and (text() = '102550100All' or . = '102550100All')]</value>
      <webElementGuid>89830530-cf93-44bf-aeff-5940d7a8c6a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
