<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>alert_Occupancy is required</name>
   <tag></tag>
   <elementGuidId>4e50fb3b-5bae-4e95-a0b3-056f04c98e8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='occupancy-error']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#occupancy-error</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6f1d4053-9d6b-4fe2-a86b-980f38775cfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>occupancy-error</value>
      <webElementGuid>bd8111d7-901e-4347-91c5-1447d9b6829d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>error invalid-feedback</value>
      <webElementGuid>d3d82143-48e0-4832-b767-330e409fd73e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Occupancy is required.</value>
      <webElementGuid>292e0dae-ded6-42d3-8750-6690d6ee7b5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;occupancy-error&quot;)</value>
      <webElementGuid>29527fc4-2f8b-4582-a511-2dbe15d5cb9e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='occupancy-error']</value>
      <webElementGuid>a81f86bb-ed16-473f-b531-bb659d324718</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/section/form/div/div/div/div/div/div[3]/div[2]/span</value>
      <webElementGuid>5623ff35-e4f5-4d1f-a4a4-efcca9510bf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Occupancy'])[1]/following::span[1]</value>
      <webElementGuid>0db72bf8-0e94-46b4-8d5a-f663a056d6bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/following::span[2]</value>
      <webElementGuid>c2cd1a60-7e0b-495a-b6c0-d390bdecd31f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='For Interface Purpose'])[1]/preceding::span[1]</value>
      <webElementGuid>11e6932f-a55c-429f-b7a5-dfec29fc5878</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Occupancy Type Code'])[1]/preceding::span[1]</value>
      <webElementGuid>8eb85f21-c191-4f71-9873-13e68543a6ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Occupancy is required.']/parent::*</value>
      <webElementGuid>dc6944ed-3982-4587-acd6-8baa16b9b28c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/span</value>
      <webElementGuid>8b4ffccd-e4ec-48f9-89e6-eed0808c57c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'occupancy-error' and (text() = 'Occupancy is required.' or . = 'Occupancy is required.')]</value>
      <webElementGuid>876ec0c2-78ba-4adf-ad20-2dc8ea971b3d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
