<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>alert_Code already exists</name>
   <tag></tag>
   <elementGuidId>b491c14e-4cf5-45b4-946f-ebb7f4f8eb95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='occupancy_type_code-error']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#occupancy_type_code-error</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2c17ebb5-a641-443d-b923-4cdbaa977b49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>occupancy_type_code-error</value>
      <webElementGuid>d3ee360f-f42d-4970-9744-39157fdcd7c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>error invalid-feedback</value>
      <webElementGuid>cda9535a-341b-4305-ae34-53c87ab71fdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Code already exists</value>
      <webElementGuid>14c0fda4-b596-408b-b581-77939c0ddb2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;occupancy_type_code-error&quot;)</value>
      <webElementGuid>843959ed-1b91-4b37-a2bf-ff66bedaf7de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='occupancy_type_code-error']</value>
      <webElementGuid>07b1e041-ee2b-4f58-abc6-85232fdb2e38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/section/form/div/div/div/div[3]/div/div/div[2]/div/div[2]/span</value>
      <webElementGuid>fcd2a744-359c-4b26-a949-efcda03dbed1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Occupancy Type Code'])[1]/following::span[1]</value>
      <webElementGuid>34f80503-4c22-45e6-a77c-dbf3b1847ea6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='For Interface Purpose'])[1]/following::span[2]</value>
      <webElementGuid>b0fbe2e2-cbcc-4e18-8b82-f4c7b03e2cb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Code already exists']/parent::*</value>
      <webElementGuid>d6a3c6da-6287-4821-ae79-bbe326dc5f02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/span</value>
      <webElementGuid>8baafa0e-ba3d-4038-89cc-97b267516398</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'occupancy_type_code-error' and (text() = 'Code already exists' or . = 'Code already exists')]</value>
      <webElementGuid>77f08ab0-afba-4821-9ffe-712e45778aa7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
