<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>breadcrumb_create new</name>
   <tag></tag>
   <elementGuidId>89e09ce5-09ba-4bb2-b113-9cd41a9377a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div/div/div/div/div/ol</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ol.breadcrumb</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ol</value>
      <webElementGuid>cba66b03-6e24-448a-99a2-41fe4e5b2bc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>breadcrumb</value>
      <webElementGuid>f040db82-8def-41eb-8788-3476d113a3d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Master Data Management Occupancy TypesCreate Occupancy Type</value>
      <webElementGuid>66248070-2eab-4636-9e73-6ce6498f3e0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;content-wrapper&quot;]/div[@class=&quot;container-fluid pb-5&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col&quot;]/div[@class=&quot;content-header&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xl&quot;]/div[@class=&quot;mb-2&quot;]/ol[@class=&quot;breadcrumb&quot;]</value>
      <webElementGuid>b8abbe7e-89ab-4568-88a7-190de1ac9d23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div/div/div/div/ol</value>
      <webElementGuid>bcf73725-fba3-4c60-8f70-ec7c32428e1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Out'])[1]/following::ol[1]</value>
      <webElementGuid>920e5a33-f1fb-4ad3-9ead-745fc138dc64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change Password'])[1]/following::ol[1]</value>
      <webElementGuid>acb37031-8a98-4264-91b8-d3bf7b9c9bc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ol</value>
      <webElementGuid>5aa86820-c30f-411a-8ba0-22e678640037</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ol[(text() = 'Master Data Management Occupancy TypesCreate Occupancy Type' or . = 'Master Data Management Occupancy TypesCreate Occupancy Type')]</value>
      <webElementGuid>fdb5f287-88d7-4a27-a1e5-b31f04fca5a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
