<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Mohon masukkan email yang valid</name>
   <tag></tag>
   <elementGuidId>3cba912f-be6f-4c24-a9e6-6dd5c4bd4638</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='login-email']/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.help-block</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bf5ac5a5-b434-4263-916d-7140ee8dc819</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>help-block</value>
      <webElementGuid>764f13c1-8c76-4324-ae0f-4004cd4ba64e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mohon masukkan email yang valid.</value>
      <webElementGuid>ec43c5d2-238b-4546-bb3f-bdd9b6cb6ebb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-email&quot;)/div[@class=&quot;form-group has-error&quot;]/div[@class=&quot;help-block&quot;]</value>
      <webElementGuid>1ed46f3e-2b95-459a-8e7c-aeb14f81bef1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login-email']/div/div</value>
      <webElementGuid>3228ec30-bae3-4f07-a64b-0199ba89bfcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masuk'])[1]/following::div[3]</value>
      <webElementGuid>165c0242-7a2f-4484-86c4-1c3b5fa184ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gapuraprima'])[1]/following::div[4]</value>
      <webElementGuid>fcb98c92-84f7-48ce-abb1-1adac4302fd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ingat Saya'])[1]/preceding::div[3]</value>
      <webElementGuid>1ffe9c88-3004-4d03-a863-afd0261cd668</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masuk'])[2]/preceding::div[5]</value>
      <webElementGuid>cf5e3ffc-4eef-40dd-baf4-386e0ac5f6bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Mohon masukkan email yang valid.']/parent::*</value>
      <webElementGuid>3a673735-1a9c-411c-887f-dd9c4ecf4507</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div</value>
      <webElementGuid>81b8b7c0-7456-4050-b728-2330c03cacd4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
