<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>enum_parent_1</name>
   <tag></tag>
   <elementGuidId>dd9347a2-3d5a-4155-a06e-7226448d8757</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.select2-results__option--highlighted</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
