<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_pagination</name>
   <tag></tag>
   <elementGuidId>43db0c30-9bba-48dc-8a30-7f008c95e9bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.custom-select</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
