<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Deactivate</name>
   <tag></tag>
   <elementGuidId>88cf50db-2cc1-41f0-93b7-f8ac4f6ef181</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@role = 'tooltip' and (text() = 'Deactivate' or . = 'Deactivate')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[(text() = 'Deactivate')]</value>
      <webElementGuid>4a261787-98e6-4bd7-9b12-5849a3ea0546</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tooltip</value>
      <webElementGuid>f2ccdd16-4d2f-4bc4-94b3-7424c5067a46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Deactivate</value>
      <webElementGuid>361cb15f-4147-487a-bff3-65b1f7f35cb5</webElementGuid>
   </webElementProperties>
</WebElementEntity>
