<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_All_img-fluid</name>
   <tag></tag>
   <elementGuidId>57c7e5ba-b070-4a27-9417-285239ca71ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn-table-action-reset > img.img-fluid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/section/div/div/div/div[2]/div/a/img</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@src = '/static/media/reset.0d97fb20.svg' and @alt = 'reset']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5bfd783b-9761-4264-acbd-29de4000dfbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/media/reset.0d97fb20.svg</value>
      <webElementGuid>cf87f4f8-c513-4a71-aa5d-47de6991550c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-fluid</value>
      <webElementGuid>8f450e17-c611-4a5d-a3d1-22865bc1d58e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>reset</value>
      <webElementGuid>fc6afd1d-ea8b-4db2-9c6f-30196f6f0fd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;content-wrapper&quot;]/div[@class=&quot;container-fluid pb-5&quot;]/section[@class=&quot;content&quot;]/div[@class=&quot;dtBIcony&quot;]/div[1]/div[@class=&quot;container-fluid pl-0&quot;]/div[@class=&quot;card card-default advanced-filter shadow-none my-2&quot;]/div[@class=&quot;card-body-filter&quot;]/a[@class=&quot;btn-table-action-reset&quot;]/img[@class=&quot;img-fluid&quot;]</value>
      <webElementGuid>4ef26b32-ed79-4abe-9536-62ef5dcf7cdf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/section/div/div/div/div[2]/div/a/img</value>
      <webElementGuid>f4906a1f-e1ad-45dd-b6c0-21d335d6fd40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='reset']</value>
      <webElementGuid>349408de-dbcf-4199-836a-25768eb6b9c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a/img</value>
      <webElementGuid>1e65193e-e251-49e7-9dd0-17ccd62b92a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/static/media/reset.0d97fb20.svg' and @alt = 'reset']</value>
      <webElementGuid>0fc3c610-5eb1-4e7b-9c0b-05eb95f45478</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
