<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Create New_datatable-download</name>
   <tag></tag>
   <elementGuidId>4c6ebb67-e50f-4c17-8bef-1378e5282ecd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#datatable-download</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='datatable-download']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2ed69e5e-b85c-45f5-a6bf-88d89ad791b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/media/download.a55d3bc6.svg</value>
      <webElementGuid>50336531-8e61-4265-a875-5cf0cbaa9118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-circle</value>
      <webElementGuid>842d59d5-371c-4e9f-8724-90ac6e7b1526</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>download</value>
      <webElementGuid>baef1e46-4881-4b51-93fb-429ac364c9e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>datatable-download</value>
      <webElementGuid>b9700a55-a4d1-487e-a50b-930ff4ca138e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;datatable-download&quot;)</value>
      <webElementGuid>b2297689-42ef-4c5e-af74-f99b751120c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='datatable-download']</value>
      <webElementGuid>7b74a911-c858-4975-83bd-86c21fcf013c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/section/div/div/div/div/div[3]/a[2]/img</value>
      <webElementGuid>19f77667-cd79-41a0-aa2c-75ad849aa3e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='download']</value>
      <webElementGuid>04a9836e-c55b-4356-ab0b-4a80107b0082</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/img</value>
      <webElementGuid>c0fdf7ad-2845-4cda-8b50-fea090ddbf51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/static/media/download.a55d3bc6.svg' and @alt = 'download' and @id = 'datatable-download']</value>
      <webElementGuid>8620e156-aacb-4b20-9b66-cf806b807a02</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
