<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_REMOVE AGE QUALIFYING TYPES_cb-th</name>
   <tag></tag>
   <elementGuidId>80ed8e8b-abd4-43c1-981a-3ab03a8b24f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cb-th</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cb-th']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1478b8c9-76eb-45b5-99ea-7083e5d058b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>d6a9c044-6f01-4e49-aba8-e6cd2270cc92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cb-th</value>
      <webElementGuid>d438cc80-541b-41f3-a19d-e113ce95b214</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-checkbox-all ml-2 mr-1</value>
      <webElementGuid>6b594901-fc26-4d4d-ad30-4f0772df2902</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cb-th&quot;)</value>
      <webElementGuid>3a7bce22-41f1-4c1c-b129-6e4e0f585c95</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cb-th']</value>
      <webElementGuid>f4b96cff-ab41-4cc4-8a73-36b8dc5000ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='DataTables_Table_0']/thead/tr/th/input</value>
      <webElementGuid>6850521e-ac4d-4f4c-801e-6b9aa4fac5d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th/input</value>
      <webElementGuid>d9ead04b-5667-45e6-83cb-5a8a978dfd08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'cb-th']</value>
      <webElementGuid>8463bd1e-feff-4954-b053-aa02f2032155</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
