<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Page_DataTables_Table_0_next</name>
   <tag></tag>
   <elementGuidId>27469b01-84dd-48ca-befe-ed8140151389</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DataTables_Table_0_next</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='DataTables_Table_0_next']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>4cd41c67-8e3d-4969-86b4-27f7ed77b6c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>paginate_button page-item next disabled</value>
      <webElementGuid>cb86a323-cbe2-411d-a0ab-e2d82bf46b3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DataTables_Table_0_next</value>
      <webElementGuid>ea0112ec-e829-4de7-b524-a1bb23d16262</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DataTables_Table_0_next&quot;)</value>
      <webElementGuid>0acba598-eac3-47dd-b1c5-61897e764023</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='DataTables_Table_0_next']</value>
      <webElementGuid>4ba55eea-0e04-4197-8eb5-0d7681256a34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DataTables_Table_0_paginate']/ul/li[3]</value>
      <webElementGuid>cdfb1618-73fe-47ba-a2b5-a8ab2b3c6aa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Page:'])[1]/following::li[3]</value>
      <webElementGuid>c3ef100b-0617-485a-ae06-872d918b3d1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Showing 1 - 2 of 2'])[1]/following::li[3]</value>
      <webElementGuid>c67b1c94-059c-4854-b47c-29a1a810c53d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Page:'])[2]/preceding::li[1]</value>
      <webElementGuid>1daa5f71-3c8a-4cff-adfd-87df29cd7906</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Powered by:'])[1]/preceding::li[1]</value>
      <webElementGuid>884fbb69-df6d-4d4a-a5f0-91e5eb7ce753</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[3]</value>
      <webElementGuid>b31d6507-aad6-4c7a-8b0a-cc5876f7595e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'DataTables_Table_0_next']</value>
      <webElementGuid>cf8cb385-5174-430c-8f22-c2961aa820f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
