<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Negotiated Fare Code_negotiated_fare_code</name>
   <tag></tag>
   <elementGuidId>150d07c2-aafa-4b30-9dc2-69358c9f1c37</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='negotiated_fare_code']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;negotiated_fare_code&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bedc2086-fb76-49cc-8ef2-779144c8e12b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>negotiated_fare_code</value>
      <webElementGuid>aa0fc2f6-ab47-43ce-a9b4-e20c66218dbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d7556081-5f4e-4b5a-8f7b-75c0710824d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>52c942ea-9f79-42fe-a92d-cd86ad8aadc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>256</value>
      <webElementGuid>22378f63-8240-461e-ac52-606cb63d970f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d77da1f2-7fd9-4fdd-9577-95079e4111d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;content-wrapper&quot;]/div[@class=&quot;container-fluid pb-5&quot;]/section[@class=&quot;content&quot;]/div[1]/form[1]/div[@class=&quot;commission-form&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col&quot;]/div[@class=&quot;form-group required  row&quot;]/div[@class=&quot;col-lg-3 col-md-4 col-12&quot;]/div[1]/div[@class=&quot;d-flex&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>24177fb1-a890-4895-8087-8c61d70ca5ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='negotiated_fare_code']</value>
      <webElementGuid>1fe5d4bc-1358-40ea-808a-1869ae23abc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/section/div/form/div/div/div/div/div/div[3]/div[2]/div/div/input</value>
      <webElementGuid>0281170a-2ec8-461e-ba8d-0c033e2f7f9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/input</value>
      <webElementGuid>964e7534-28bd-4822-8638-5694200e18b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'negotiated_fare_code' and @type = 'text']</value>
      <webElementGuid>a39a5fc6-5fde-4974-b743-d722fe566a9d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
